run:
  timeout: "5m"
  skip-files:
  - tools/tools.go

linters:
  disable-all: true
  enable:
  - goimports
  - gofmt
  - gofumpt
  - whitespace
  - staticcheck
  - ineffassign
  - unused
  - misspell
  - unconvert
  - errcheck

linters-settings:
  goimports:
    local-prefixes: github.com/nitrictech
  govet:
    check-shadowing: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
