run:
  timeout: "5m"
  skip-files:
  - tools/tools.go

linters:
  disable-all: true
  enable:
  - goimports
  - gofmt
  - whitespace
  - staticcheck
  - structcheck
  - ineffassign
  - varcheck
  - unused
  - deadcode
  - misspell
  - unconvert
  - errcheck

linters-settings:
  goimports:
    local-prefixes: github.com/nitrictech
  govet:
    check-shadowing: false
  staticcheck:
    checks: ["all", "-SA1019"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
