version: 0.2
phases:
  build:
    commands:
      - echo "Creating database ${DB_NAME}"
      - export PGPASSWORD=${DB_MASTER_PASSWORD}
      - psql -h ${DB_CLUSTER_ENDPOINT} -U ${DB_MASTER_USERNAME} -d nitric -c "CREATE DATABASE \"${DB_NAME}\"" || echo "database ${DB_NAME} already exists"
