run:
  timeout: "5m"
  skip-files:
    - tools/tools.go
  skip-dirs:
    - deploytf/generated
  go: 1.18

linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - govet
    - gofumpt
    - whitespace
    # - staticcheck
    - ineffassign
    - unused
    - misspell
    - unconvert
    - errcheck
    - errorlint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - deploytf/generated

linters-settings:
  govet:
    check-shadowing: false
  exclude:
    - "^deploytf/generated/.*"
