name: Release Contracts
on:
  release:
    types: [published]

jobs:
  # Bump the membrane version
  contract_release:
    name: Add contracts to release
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Tarball the contracts repository
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'tar'
          filename: 'proto.tgz'
          path: nitric

      # Upload contract tarball to the releases
      - name: Upload Contracts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NITRIC_BOT_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./proto.tgz
          asset_name: proto.tgz
          asset_content_type: application/tar+gzip
  