name: Production Release
on:
  push:
    branches:
      - main
jobs:
  # Bump the membrane version
  version_bump:
    name: Bump Version and Create Release
    runs-on: ubuntu-latest
    outputs:
      version_id: ${{ steps.tag_version.outputs.new_tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.NITRIC_BOT_TOKEN }}
