name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.GOLANG_TOKEN}}
        submodules: recursive
    - name: Setup Go
      uses: actions/setup-go@v2-beta      
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - name: Install modules
      run: make install-tools
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup local DynamoDB
      run: make install-test-tools
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@master
    - name: Install Google Cloud SDK components
      run: yes | gcloud components install beta cloud-firestore-emulator
    - name: Check Source License Headers
      run: make license-header-check
    - name: Run Tests
      run: make test
    - name: Check Dependency Licenses
      run: make license-check